# Generated by Django 3.2.9 on 2021-11-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='github_link',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
